#!/bin/bash
# Set hostname
if [ -z $1 ]; then
    echo "No hostname provided"
    exit
fi
sudo hostnamectl hostname $1

sudo flatpak remote-modify --enable flathub
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Replace fedora gnome apps with flathub 
#fedora_remote_apps=$(flatpak list --columns=application,origin | grep fedora | grep org.gnome | awk '{ print $1 }')
#
#flatpak uninstall $fedora_remote_apps
#flatpak install flathub $fedora_remote_apps

flatpak install flathub\
    org.mozilla.firefox\
    org.videolan.VLC\
    com.valvesoftware.Steam\
    org.gnome.Lollypop

sudo flatpak override --socket=wayland --env=MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox

if  ! rpm-ostree status | grep RemovedBasePackages | grep firefox ; then
    sudo rpm-ostree override remove firefox
fi

sudo rpm-ostree --idempotent install kitty

# Copy system config files
sudo rsync -rv ./system/ /

# Enable systemd services
sudo rpm-ostree reload
sudo systemctl enable rpm-ostreed-automatic.timer --now
sudo systemctl enable sshd

# Add udev rules for steam
git clone https://github.com/ValveSoftware/steam-devices /tmp/steam-devices
sudo cp /tmp/steam-devices/*.rules /etc/udev/rules.d/.
rm -rf /tmp/steam-devices

if [ "$1" == "razerbook" ]; then
    sudo rpm-ostree kargs --append-if-missing=i915.enable_psr=0
fi
